export const ERROR_MES_SET = "ERROR_MES_SET"
export const ERROR_MES_REMOVE = "ERROR_MES_REMOVE"

export const MOVIE_DETAIL_SET = "MOVIE_DETAIL_SET"
export const MOVIE_LATEST_SET = "MOVIE_LATEST_SET"
export const MOVIE_NOW_PLAYING_SET = "MOVIE_NOW_PLAYING_SET"
export const MOVIE_POPULAR_SET = "MOVIE_POPULAR_SET"
export const MOVIE_TOP_RATED_SET = "MOVIE_TOP_RATED_SET"
export const MOVIE_UPCOMING_SET = "MOVIE_UPCOMING_SET"

export const MOVIE_DETAIL_GET = "MOVIE_DETAIL_GET"
export const MOVIE_LATEST_GET = "MOVIE_LATEST_GET"
export const MOVIE_NOW_PLAYING_GET = "MOVIE_NOW_PLAYING_GET"
export const MOVIE_POPULAR_GET = "MOVIE_POPULAR_GET"
export const MOVIE_TOP_RATED_GET = "MOVIE_TOP_RATED_GET"
export const MOVIE_UPCOMING_GET = "MOVIE_UPCOMING_GET"

